import Head from "next/head";
import React from "react";
import "react-toastify/dist/ReactToastify.css";
import { userApi } from "../api/user";
import { ToastContainer, toast } from "react-toastify";
import { useDispatch, useSelector } from "react-redux";
import { logout, selectAuth } from "../features/auth/authSlice";
import Link from "next/link";
import Image from "next/image";

const Layout = ({ children }) => {
  const dispatch = useDispatch();
  const auth = useSelector(selectAuth);
  const { isLogin } = auth;
  const notify = (err) => toast.error(err);
  const handleLogout = async () => {
    await userApi.logout();
    notify("Logout Success");
    dispatch(logout({}));
  };
  return (
    <div className="flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer />

      <header className="fixed top-0 left-0 right-0 h-14 shadow-lg z-10 bg-white flex items-center">
        <nav className="container mx-auto items-center flex justify-between	">
        <Link href="/">
          <a className="flex items-center">
            <Image
              className="rounded-full"
              src="https://i.pinimg.com/564x/57/15/a0/5715a05309ebfdf2ddd64e09735478b1.jpg"
              alt=""
              width={48}
              height={48}
            />
            <span className="ml-2">KUTE</span>
          </a>
        </Link>
        <div className="flex gap-3">
          <Link href='/'>
          <a>Home</a>
          </Link>
          <Link href='/'>
          <a>About</a>
          </Link>
          <Link href='/'>
          <a>Contact</a>
          </Link>

        </div>
        <div className="flex gap-3">
          <button className="bg-red-500 text-white h-10 w-20 rounded-full">
            Log in
          </button>
          <button className="h-10 w-24 bg-slate-200 rounded-full">
            Sign up
          </button>
        </div>
        </nav>

      </header>
      <main className="py-2 h-full flex flex-col items-center justify-center mt-14">
        {children}
      </main>
      {/* <footer className="container mx-auto bg-black h-12 text-white">
        This is footer
      </footer> */}
    </div>
  );
};

export default Layout;
